# Generated by Django 3.2.9 on 2021-11-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=125, null=True)),
                ('Adress', models.CharField(blank=True, max_length=125, null=True)),
                ('director_name', models.CharField(blank=True, max_length=125, null=True)),
                ('director_number', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=125, null=True)),
                ('first_name', models.CharField(blank=True, max_length=123, null=True)),
                ('username', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='user', max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savatcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sold_price', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='progres', max_length=55, null=True)),
                ('sold_date', models.DateTimeField(auto_now_add=True)),
                ('sold_discout', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.product')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profile')),
            ],
        ),
    ]
