# Generated by Django 3.2.9 on 2021-11-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
