# Generated by Django 3.2.9 on 2021-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_profile_discout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savatcha',
            name='sold_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='sold_discout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='status',
            field=models.CharField(default='progress', max_length=55, null=True),
        ),
    ]
